
OBJECTS = ArabicToRomanConverter.o RomanToArabicConverter.o RomanNumeralCalculator.o  

.PHONY: all

all: $(OBJECTS)

RomanNumeralCalculator.c: RomanNumeralCalculator.h 
ArabicToRomanConverter.c: ArabicToRomanConverter.h
RomanToArabicConverter.c: RomanToArabicConverter.h
